//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblAccountNumber;

        protected global::System.Web.UI.WebControls.Label lblFullName;

        protected global::System.Web.UI.WebControls.Label lblCurrentBalance;

        protected global::System.Web.UI.WebControls.Label lblTotalSent;

        protected global::System.Web.UI.WebControls.Label lblDateRegistered;

        protected global::System.Web.UI.WebControls.Repeater repNotifications;

        protected global::System.Web.UI.WebControls.Panel pnlNoNotifications;
    }
}
