//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney
{
    public partial class Site
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedOut;

        protected global::System.Web.UI.WebControls.PlaceHolder phLoggedIn;

        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
    }
}
