//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney.Transactions
{
    public partial class Deposit
    {
        protected global::System.Web.UI.WebControls.Label lblCurrentBalance;

        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        protected global::System.Web.UI.WebControls.Button btnDeposit;
    }
}
