//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney.Transactions
{
    public partial class SendMoney
    {
        protected global::System.Web.UI.WebControls.TextBox txtRecipientAccount;

        protected global::System.Web.UI.WebControls.Button btnVerifyRecipient;

        protected global::System.Web.UI.WebControls.Panel pnlRecipientDetails;

        protected global::System.Web.UI.WebControls.Label lblRecipientAccount;

        protected global::System.Web.UI.WebControls.Label lblRecipientName;

        protected global::System.Web.UI.WebControls.HiddenField hfRecipientUserId;

        protected global::System.Web.UI.WebControls.TextBox txtAmount;

        protected global::System.Web.UI.WebControls.TextBox txtPasswordConfirm;

        protected global::System.Web.UI.WebControls.Button btnSendMoney;
    }
}
