//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney.Reports
{
    public partial class StatementOfAccount
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        protected global::System.Web.UI.WebControls.Button btnFilter;

        protected global::System.Web.UI.WebControls.GridView gvStatement;
    }
}
