//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudMoney.Auth
{
    public partial class Register
    {
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;

        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirm;

        protected global::System.Web.UI.WebControls.CompareValidator cvPasswordMatch;

        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
